export const animals = [
  "Aardvark", "Albatross", "Alligator", "Alpaca", "Antelope", "Armadillo", "Axolotl", "Baboon", "Badger", "Barracuda",
  "Bat", "Beaver", "Bison", "Boa", "Boar", "Buffalo", "Butterfly", "Camel", "Capybara", "Caribou",
  "Cassowary", "Cat", "Caterpillar", "Cheetah", "Chameleon", "Chimpanzee", "Cobra", "Condor", "Cougar", "Coyote",
  "Crab", "Crane", "Crocodile", "Crow", "Deer", "Dingo", "Dodo", "Dog", "Dolphin", "Donkey",
  "Dragonfly", "Duck", "Eagle", "Echidna", "Eel", "Elephant", "Elk", "Emu", "Falcon", "Ferret",
  "Finch", "Firefly", "Flamingo", "Fox", "Frog", "Gazelle", "Gecko", "Gerbil", "Giraffe", "Goat",
  "Goose", "Gopher", "Gorilla", "Grasshopper", "Hamster", "Hare", "Hawk", "Hedgehog", "Heron", "Hippopotamus",
  "Hornet", "Horse", "Hummingbird", "Hyena", "Iguana", "Impala", "Jackal", "Jaguar", "Jellyfish", "Kangaroo",
  "Kingfisher", "Koala", "Komodo", "Krill", "Lark", "Lemur", "Leopard", "Liger", "Lion", "Lizard",
  "Llama", "Lobster", "Lynx", "Macaw", "Magpie", "Mallard", "Manatee", "Mandrill", "Mantis", "Meerkat",
  "Mink", "Mole", "Mongoose", "Monkey", "Moose", "Mosquito", "Moth", "Mouse", "Mule", "Narwhal",
  "Newt", "Nightingale", "Ocelot", "Octopus", "Okapi", "Opossum", "Orangutan", "Orca", "Ostrich", "Otter",
  "Owl", "Ox", "Panda", "Panther", "Parrot", "Peacock", "Pelican", "Penguin", "Phoenix", "Pig",
  "Pigeon", "Platypus", "PolarBear", "Porcupine", "Porpoise", "Possum", "Prawn", "Puffin", "Puma", "Quail",
  "Quokka", "Rabbit", "Raccoon", "Ram", "Rat", "Raven", "Reindeer", "Rhino", "Robin", "Rooster",
  "Salamander", "Salmon", "Scorpion", "Seahorse", "Seal", "Shark", "Sheep", "Shrimp", "Skunk", "Sloth",
  "Snail", "Snake", "Sparrow", "Spider", "Squid", "Squirrel", "Starfish", "Stingray", "Stork", "Swan",
  "Tapir", "Tarsier", "TasmanianDevil", "Termite", "Tiger", "Toad", "Toucan", "Trout", "Turkey", "Turtle",
  "Viper", "Vulture", "Wallaby", "Walrus", "Wasp", "Weasel", "Whale", "Wildcat", "Wolf", "Wombat",
  "Woodpecker", "Worm", "Wren", "Yak", "Zebra", "Zebu", "Zorilla", "Myna", "Bonobo", "Tamarin"
];

export const adjectives = [
  "Adorable", "Agile", "Alert", "Amazing", "Ambitious", "Ancient", "Angry", "Artful", "Awesome", "Awkward",
  "Balanced", "Beautiful", "Big", "Blissful", "Bold", "Bouncy", "Brave", "Bright", "Brisk", "Bubbly",
  "Busy", "Calm", "Caring", "Clever", "Clumsy", "Cool", "Cosmic", "Crazy", "Crispy", "Curious",
  "Cute", "Dainty", "Dapper", "Daring", "Dazzling", "Delicate", "Delightful", "Determined", "Dizzy", "Dreamy",
  "Eager", "Easygoing", "Electric", "Elegant", "Energetic", "Enthusiastic", "Epic", "Excited", "Exotic", "Fair",
  "Fancy", "Fast", "Fearless", "Feisty", "Fierce", "Flaky", "Flashy", "Fluffy", "Focused", "Free",
  "Fresh", "Friendly", "Frisky", "Funky", "Fuzzy", "Gallant", "Giddy", "Gigantic", "Glamorous", "Gleeful",
  "Glorious", "Goofy", "Graceful", "Gracious", "Grand", "Gritty", "Groovy", "Grumpy", "Happy", "Hardy",
  "Hasty", "Helpful", "Heroic", "Hilarious", "Honest", "Humble", "Humming", "Hyper", "Icy", "Imaginative",
  "Incredible", "Inquisitive", "Intense", "Inventive", "Jazzy", "Jolly", "Joyful", "Jumpy", "Keen", "Kind",
  "Lively", "Lofty", "Lucky", "Luminous", "Mad", "Magical", "Majestic", "Mellow", "Merry", "Mighty",
  "Mini", "Mirthful", "Misty", "Modern", "Moody", "Mysterious", "Nervy", "Nifty", "Nimble", "Noisy",
  "Nutty", "Odd", "Optimistic", "Outstanding", "Peculiar", "Peppy", "Perky", "Persistent", "Playful", "Pleasant",
  "Plucky", "Polished", "Powerful", "Precious", "Proud", "Quick", "Quirky", "Radiant", "Rare", "Reckless",
  "Relaxed", "Reliable", "Resilient", "Robust", "Rowdy", "Savage", "Sassy", "Saucy", "Savvy", "Sharp",
  "Shiny", "Silly", "Sincere", "Skilled", "Sleepy", "Slippery", "Smart", "Smiling", "Snappy", "Sneaky",
  "Snug", "Soft", "Sparkly", "Speedy", "Spicy", "Spunky", "Steady", "Stealthy", "Strong", "Stubborn",
  "Sunny", "Surly", "Sweet", "Swift", "Tame", "Tasty", "Teeny", "Tenacious", "Thrifty", "Timid",
  "Tiny", "Tricky", "Trusty", "Unique", "Upbeat", "Vast", "Vibrant", "Vigilant", "Wacky", "Wavy",
  "Weird", "Wicked", "Wild", "Wise", "Witty", "Wobbly", "Wonderful", "Zany", "Zesty", "Zippy"
];